name: Terraform Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.8.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
